import type { Metadata } from "next";
import "./global.scss";
import { Navbar } from "@/app/components/Navbar";
import { getPortfolioConfig } from "@/app/services/portfolio";
import { Tektur } from "next/font/google";

const tektur = Tektur({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-tektur",
});

export const metadata: Metadata = {
  title: "Dival Sehgal",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getPortfolioConfig();

  return (
    <html lang="en">
      <body className={`${tektur.variable}`}>
        <Navbar navbar={data.config.navbar} />
        {children}
      </body>
    </html>
  );
}
