import type { Metadata } from "next";
import "./styles/index.scss";

import { Tektur } from "next/font/google";

const tektur = Tektur({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-tektur",
});

export const metadata: Metadata = {
  title: "Dival Sehgal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${tektur.variable}`}>{children}</body>
    </html>
  );
}
